# Generated by Django 4.2.3 on 2023-07-07 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('agirlik', models.IntegerField()),
                ('kategori', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'İHA',
                'verbose_name_plural': 'İHA Listesi',
            },
        ),
        migrations.CreateModel(
            name='Kiralama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atarihi', models.DateTimeField()),
                ('vtarihi', models.DateTimeField()),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykar.iha')),
                ('uye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiralama',
                'verbose_name_plural': 'Kiralama Kayıtları',
            },
        ),
    ]
