# Generated by Django 4.2.3 on 2023-07-08 14:33

import baykar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykar', '0003_profil_name_profil_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='foto',
            field=models.ImageField(blank=True, default='profil_foto/6b9f250c.jpg', null=True, upload_to=baykar.models.rename_image),
        ),
    ]
