# Generated by Django 4.2.3 on 2023-07-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykar', '0004_alter_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralama',
            name='atarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiralama',
            name='vtarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
