# Generated by Django 4.2.3 on 2023-07-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykar', '0005_alter_kiralama_atarihi_alter_kiralama_vtarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralama',
            name='atarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kiralama',
            name='vtarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
