# Generated by Django 4.2.3 on 2023-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykar', '0006_alter_kiralama_atarihi_alter_kiralama_vtarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiralama',
            name='asaati',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kiralama',
            name='vsaati',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
